version: '2'
volumes:
    resin-data:
services:
  openocd:
    build: ./openocd
    restart: no
    volumes:
      - 'resin-data:/data'
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'